# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: deeptech consulting
email: post@deeptechconsulting.no
description: >- # this means to ignore newlines until "baseurl:"
  deeptech consulting is an Oslo-based tech company offering consulting services on topics
  such as machine learning, data science, and scientific computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  consultants:
    order:
      - simon.md
      - timo.md
  services:
  partners:
    order:
      - fhi.md
      - porterbuddy.md
      - futureready.md
      - seald.md
      - a_la_calc.md
      - imerso.md
      - mettle.md
  projects:
  skills:
    order:
      - technical_leadership.md
      - machine_learning.md
      - data_science.md
      - optimization.md
      - scientific_computing.md
  techstack:
    order:
      - python.md
      - jupyter.md
      - pandas.md
      - tensorflow.md
      - scikit_learn.md
      - fenics.md
      - ruby_on_rails.md
      - docker.md
      - mysql.md
      - mongodb.md
      - optaplanner.md
      - azure.md


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
